### ISSUE TITLE
http://redis-store.org is down

### ISSUE THREAD

**Issue by steakknife** [redis-store/redis-store.github.io#1]
http://redis-store.org appears to need DNS changes:

Replace one A record (204.232.175.78) with two A records

192.30.252.153
192.30.252.154

per https://help.github.com/articles/troubleshooting-custom-domains/

**Comment by tubbo** [comment]
We're gonna talk about redis-store.org in general here...personally I don't see the point. redis-store.github.io should work too. Also don't think we need an email address for support, there's github issues and I'm not interested in opening another support channel.

If anyone rejects this notion I'll happily have a discussion, but at this point I'm leaning towards removing references to redis-store.org and just using the github given domain.

**Comment by marceloboeira** [comment]
@tubbo I guess we need to remove the CNAME only, then the redis-store.github.io will work just fine!

**Comment by tubbo** [comment]
@marceloboeira yep, but of course we also need to remove links to the non-working redis-store.org :) i can do that right now.

**Comment by marceloboeira** [comment]
@tubbo yeah, nice!

**Comment by marceloboeira** [comment]
We can close this after we remove the links

**Comment by steakknife** [comment]
A working doc site would be a major improvement.
