### ISSUE TITLE
Restore core contributors support email

### ISSUE THREAD

**Issue by steakknife** [redis-store/redis-store.github.io#2]
Probably means the underlying Gmail account changed or went away.

**Comment by tubbo** [comment]
This is basically the same issue as #1 so I'm closing. It's related to redis-store.org's DNS either lapsing or no longer being in our control.

**Comment by steakknife** [comment]
People are currently unable to submit private feedback or security issues.

**Comment by steakknife** [comment]
Something like redis-store@gmail.com which forwards to a private core contributors email list would probably be the way to go to solve manageability headaches.

**Comment by tubbo** [comment]
@steakknife Reopening this so we can start a discussion on whether this is necessary. Personally, I believe in having all discussion out in the open to demonstrate that this project is for you, and by you. Anyone can contribute, and we encourage all forms of it, especially discussion. Having some of that discussion in private may be necessary, but I'll let the rest of the contributors help make that decision.
